### ISSUE TITLE
add photoLocalurl() and savephoto() methods in Title class (was Caching images)

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#117]
I don't understand how images are cached.

I've tried to use various methods in Title class ( photo(), mainphoto()).
1/ They accurately find the pictures (those at https://m.media-amazon.com/images/*)
2/ No cache is created in my cache folder.

I suspect you removed the images caching system, since I can't find methods like savephoto(). Is there any reason? It saves queries to IMDb and is much faster.

**Comment by duck7000** [comment]
Alright here is how i think it works

First of all the request from, for example photo(), are cached but in that cache only the url is cached, not the actual image
I didn't remove any image caching system as far as i know, but i did removed savephoto() and photoLocalUrl() as i don't need them.

We discussed earlier about savephoto() and photolocalurl() been removed

I save the images with curl in my program so i don't need those methods

my photo() method returns exactly what it did in the imdbphp version, a image url, which will be cached

I suspect that you used to use savephoto() or photoLocalUrl to save the actual image?

**Comment by jcvignoli** [comment]
> I didn't remove any image caching system as far as i know, but i did removed savephoto() and photoLocalUrl() as i don't need them.
I don't get your reponse. You did remove the image caching methods. I understand you may don't need them, but you removed the caching system.

>I suspect that you used to use savephoto() or photoLocalUrl to save the actual image?
Absolutely. photo_localurl() method.

From the [other thread](https://github.com/duck7000/imdbGraphQLPHP/issues/118):
>Like saving images i don't think that is a function of a library but imdbphp did it anyway
I don't get you. This is caching, why would it be ok to cache text but not images?

>So i will add those debug entry's in cache class and add Exception class, if that is done please remove those from your PR as it makes it needlessly more complicated as it already is
1/ Those debug lines are actually the whole interest of adding the Logger in Cache ;)
2/ I added the Exception class because in your environnement it may work, but in most environments it shouldnt. Either:
a/ one should add a `use \Exception;` at the begining of the class, with the backslash saying to call the PHP Exception class (outside IMDB namespace)
b/ use an extra Exception class. Pretty standard, it extends the Exception to any class. Most used.
3/ I've no idea how to remove a pull, but I closed it.

>And exception class is not needed, php has its own one. (I tested this with or without Exception class)
>So if i create a error (wrong dir name) in both cases the same exception is thrown. But if you want i can add it anyway as it won't hurt.
There were two different Exceptions in the pull, I'm not sure I'm getting you.

>If you are after a complete copy of imdbphp i'm not sure i will do that. I already are far off my original idea of a very stripped down version and i don't want to add stuff i don't understand or is far beyond the scope of this project.
I've the feeling that you see your project mainly as a personal project dedicated to your needs. Please clarify if you're not expecting people to suggest improvements, because I don't understand what have I suggested that would be beyond "the scope of your project"
I need to understand what you mean, thanks. I may have misunderstood your project.

**Comment by duck7000** [comment]
I think you don't understand how this works

Caching system works, exactly like it does in imdbphp.
In imdbphp the photo url from photo() is cached but only as url not the actual image. My method does exactly the same.
So i don't get why you think somewhere i removed the cache system? In both imbphp and imdbGraphQLPHP this works exactly the same.
You consider those save functions as cache? Or use them as cache? which they are not in my view, they can be used to save a image.
In my view this is not within the scope of a library? A library collects data which can be used elsewhere.
So i don't understand why you don't want to save the images inside your program?
Can you explain to me why you think saving images does belong to a library?

photo_localurl() is a save function not a cache function, but you use it as cache. I don't know how you use the data from this library but you should use that data in your program/app/whatever to save those images?

I will add those debug entry's and the exception class. Apparently i'm lucky it works in my environment, don't know why though. But i'll take your word for it as i don't know enough about this.

My project started as a personal very stripped down version of imdbphp, that is absolutely true.
But as more users asked to include more and more methods, classes, logging, caching etc i decided to make it a more complete version.
I included all those stuff but with in mind that the defaults are tailored to my personal needs with the possibility to override those.

**I do listen to people with improvements, including you, for sure!**
But you also have to understand that i don't want to make a exact copy of imdbphp, so yes there are some things/methods i left out from who i think don't belong in a library

**Comment by jcvignoli** [comment]
Cool, thanks for your response. I was wondering whether it would be useful for me to report back and suggest improvements, so I will continue.
1/ The idea is not to get an exact copy of IMDbPHP. imdbGraphQLPHP actually goes further than IMDbPHP, since you developped new classes. The thing is that some specific functions (like the cache) are actually very usefull for libraries that are using your own library.
2/ Regarding the pictures as cache: well, the whole point of a caching system is to not make an extra request. It a/ saves time b/ saves bandwith, and most importantly c/ saves the queries made to IMDb. IMDb actually temporarly bans users that make too many requests. It's also, in my humble opinion, unfair to make more requests that needed to a site that offers for free access to a huge data.
So, caching the actual pictures instead of caching the pictures URL is more fair, faster, and more efficient.
Saving the pictures for a later use IS a caching system. That's saving data (imdbGraphQLPHP already saves movie's information, pictures are information).

I hope I clarified why photo_localurl() is a caching method. I believe saying that "saving pictures" is not caching them is incorrect. Now, shouldn't you want to cache pictures for some personal reason, I would perfectly understand, no problem.

**Comment by duck7000** [comment]
I do understand that caching the actual image saves requests etc, that is not the point.
In my view photo_localurl() is a save function, not a cache function.
But as you explained above it can be used for caching images.
Confusing it is, and whether this should be included in this library or not is a open question, agree?

So okay i will include those methods for those who need it, caching the image url from photo() will remain as it is included in the cache system just like all methods do. This won't harm anyone.

I will look in to this asap

**Comment by jcvignoli** [comment]
> Confusing it is, and whether this should be included in this library or not is a open question, agree?

No from my point of view. Pictures are saved to be displayed later, just like any data retrieved from IMDb.
But I guess it's a matter of perspective! ;)

> I will look in to this asap

Thanks man!

**Comment by duck7000** [comment]
well all methods that includes image urls work the same way, the url is cached.
So if you use other methods you have to use photo_localurl() on all of them.

And agree to disagree is also fine, it is a matter of perspective indeed

**Comment by duck7000** [comment]
I added those methods in latest commit

So please check the working yourself as this is not tested.
It is exactly the same as the imdbphp version with one exception:
I renamed photo_localurl to photoLocalurl

I found those methods kind of weird though:

1. It savephoto() checks if the image is jpg, gif or bmp? gif and bmp never occur in GraphQL, it is always jpg (one exception for logos, those are png)
2. assume that the image is actual bmp, then photoLocalurl saves that image always as .jpg..?

So testing, bug fixing or other issues has to come from you as nobody else probably is going to use this

**Comment by jcvignoli** [comment]
I'm testing it, this is great.

> assume that the image is actual bmp, then photoLocalurl saves that image always as .jpg..?

Well, I will suggest something different in the future. As soon as I get back some functions for testing. And will have to learn how to make pulls.

> This code is also weird in my view, it saves the image in photdir but returns image path from photoroot?

Yes, it's a longstanding bug. A correct method would be ( I replaced the two first photodir by photoroot)

```
    public function photoLocalurl($thumb = true)
    {
        if ($thumb) {
            $ext = "";
        } else {
            $ext = "_big";
        }
        if (!is_dir($this->config->photoroot)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory does not exist!<BR>");
            return false;
        }
        $path = $this->config->photoroot . $this->imdbid() . "{$ext}.jpg";
        if (file_exists($path)) {
            return $this->config->photoroot . $this->imdbid() . "{$ext}.jpg";
        }
        if (!is_writable($this->config->photodir)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory lacks write permission!<BR>");
            return false;
        }
        if ($this->savephoto($path, $thumb)) {
            return $this->config->photoroot . $this->imdbid() . "{$ext}.jpg";
        }
        return false;
    }
```

Please note that I also took the opportunity to fix an extra bug: this should be `$this->config->photodir` instead of `$this->photodir` (an extra `->config`). Same for photoroot.

Would it be possible to add it to Name class as well?

**Comment by jcvignoli** [comment]
I fixed the method.

**Comment by jcvignoli** [comment]
I found a small needed improvement. Since both pictures (Name+Title) have the same name (6-7 numbers+jpg), it would be welcome to add an extra bit to know what is a Title and a Name.
I suggest to add 'tt' for Title and "nm" for Name.

The above method would now read as:

```
    public function photoLocalurl($thumb = true)
    {
        if ($thumb) {
            $ext = "";
        } else {
            $ext = "_big";
        }
        if (!is_dir($this->config->photoroot)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory does not exist!<BR>");
            return false;
        }
        $path = $this->config->photoroot . 'tt' . $this->imdbid() . "{$ext}.jpg";
        if (file_exists($path)) {
            return $this->config->photodir . 'tt' . $this->imdbid() . "{$ext}.jpg";
        }
        if (!is_writable($this->config->photoroot)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory lacks write permission!<BR>");
            return false;
        }
        if ($this->savephoto($path, $thumb)) {
            return $this->config->photodir . 'tt' . $this->imdbid() . "{$ext}.jpg";
        }
        return false;
    }
```
The Name class would just have 'nm' in the 3 strings that have 'tt'.

**Comment by duck7000** [comment]
> Would it be possible to add it to Name class as well?

yes but please make new issues for new requests for other classes, otherwise i can't track it all down anymore

**Comment by duck7000** [comment]
> Yes, it's a longstanding bug. A correct method would be to check if photoroot exists (which is a path), then return photodir (which is an URL)

Mm i still don't understand why/how save the image to one dir but return a image url from another dir?
I mean if you save the image in directory A how can you have a return path from directory B?

**Comment by duck7000** [comment]
> I found a small needed improvement. Since both pictures (Name+Title) have the same name (6-7 numbers+jpg), it would be welcome to add an extra bit to know what is a Title and a Name. I suggest to add 'tt' for Title and "nm" for Name.
> 
> The above method would now read as:
> 
> ```
>     public function photoLocalurl($thumb = true)
>     {
>         if ($thumb) {
>             $ext = "";
>         } else {
>             $ext = "_big";
>         }
>         if (!is_dir($this->config->photoroot)) {
>             $this->debug_scalar("<BR>***ERROR*** The configured image directory does not exist!<BR>");
>             return false;
>         }
>         $path = $this->config->photoroot . 'tt' . $this->imdbid() . "{$ext}.jpg";
>         if (file_exists($path)) {
>             return $this->config->photodir . 'tt' . $this->imdbid() . "{$ext}.jpg";
>         }
>         if (!is_writable($this->config->photoroot)) {
>             $this->debug_scalar("<BR>***ERROR*** The configured image directory lacks write permission!<BR>");
>             return false;
>         }
>         if ($this->savephoto($path, $thumb)) {
>             return $this->config->photodir . 'tt' . $this->imdbid() . "{$ext}.jpg";
>         }
>         return false;
>     }
> ```
> 
> The Name class would just have 'nm' in the 3 strings that have 'tt'.

I added it like this `"tt$this->imdbid()"` but please test the working.

**Comment by duck7000** [comment]
And if you are going to make new PR please keep it strictly to a specific issue or problem, don't mix up things as it is impossible for me to track the changes and i will be forced to reject

**Comment by jcvignoli** [comment]
> I added it like this "tt$this->imdbid()" but please test the working.

This can't work. if you abolutely want to join the var and the 'tt' string (less readability in my opinion) the var should be encapsulated this way:

`"tt{$this->imdbid()}"`

> And if you are going to make new PR please keep it strictly to a specific issue or problem, don't mix up things as it is impossible for me to track the changes and i will be forced to reject

I stopped making PR until I better understand how it works. I don't understand why you bring this issue again, I haven't made a new PR?

**Comment by duck7000** [comment]
Well  i didn't  know that, it is possible with a variable (see line 3314 in Title class) and assumed the same goes for a function call but apparently this is not true, i'll change that 

please read the above again, i said **if** So if you are planning to make new PR's keep it strictly to the point, that is all that i am saying

**Comment by jcvignoli** [comment]
the method in latest commit is wrong, photodir and photoroot are interverted.

The method should be as following:

```
    public function photoLocalurl($thumb = true)
    {
        if ($thumb) {
            $ext = "";
        } else {
            $ext = "_big";
        }
        if (!is_dir($this->config->photoroot)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory does not exist!<BR>");
            return false;
        }
        $path = $this->config->photoroot . "tt{$this->imdbid()}" . "{$ext}.jpg";
        if (file_exists($path)) {
            return $this->config->photodir . "tt{$this->imdbid()}" . "{$ext}.jpg";
        }
        if (!is_writable($this->config->photoroot)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory lacks write permission!<BR>");
            return false;
        }
        if ($this->savephoto($path, $thumb)) {
            return $this->config->photodir . "tt{$this->imdbid()}" . "{$ext}.jpg";
        }
        return false;
    }
```

> Well i didn't know that, it is possible with a variable (see line 3314 in Title class) and assumed the same goes for a function call but apparently this is not true, i'll change that

I closed the pull since I've no idea how to properly manage a fork. I will get back to it at some point, as soon as I properly learned how to use it ;)

**Comment by duck7000** [comment]
Hard to spot the changes you made, this is fixed in latest commit

**Comment by duck7000** [comment]
I made a new issue for adding those image save functions to the Name class

**Comment by jcvignoli** [comment]
I changed the title and close this issue, everything works, thanks!

**Comment by duck7000** [comment]
Nice teamwork though!
